version: '3'

services:
    mysql:
        image: mysql
        hostname: develop-mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456123
            TZ: Asia/Shanghai
        ports:
            - 3306:3306
        volumes:
            - D:\database\mysql\data:/var/lib/mysql
            - D:\database\mysql\config/my.cnf:/etc/mysql/my.cnf
        command: --max_connections=1000
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --default-authentication-plugin=mysql_native_password
