services:
  mysql:
    image: mysql:latest
    hostname: develop-mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: go_gateway
      MYSQL_ROOT_PASSWORD: 123456123
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql-files:/var/lib/mysql-files
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
  redis:
    image: redis:latest
    hostname: develop-redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
# auth !Shizhenfei123
