services:
  mysql:
    image: mysql:latest
    hostname: develop-mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: go_gateway
      MYSQL_ROOT_PASSWORD: 123456123
      TZ: Asia/Shanghai
    ports:
      - 0.0.0.0:3306:3306
    volumes:
      - ./data/mysql-files:/var/lib/mysql-files
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
  redis:
    image: redis:latest
    hostname: develop-redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 0.0.0.0:6379:6379
    volumes:
      - ./data/redis:/data
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
  Etcd:
    image: "bitnami/etcd:latest"
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 0.0.0.0:2379:2379
      - 0.0.0.0:2380:2380
# auth !Shizhenfei123
