DriverName: mysql
Mysql:
    host: 192.168.1.13
    port: 3306
    username: root
    password: 123456123
    database: go_gateway
Redis:
    host: 192.168.1.13
    port: 6379
    password: "!Shizhenfei123"
    database: 0
Jwt:
    key: alskjdahfAKLSFJDLlfaslhLSHljadfhlaSJhflakl
    issuer: stone2401
    time_out: 300
Cluster:
    ip: 0.0.0.0
    port: 29193
    ssl_port: 4880
Etcd:
    endpoints:
        - 192.168.1.13:2379
