DriverName: mysql
Mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456123
    database: go_gateway
Redis:
    host: localhost
    port: 6379
    password: "!Shizhenfei123"
    database: 0
Jwt:
    key: alskjdahfAKLSFJDLlfaslhLSHljadfhlaSJhflakl
    issuer: stone2401
    time_out: 300
Cluster:
    ip: 0.0.0.0
    port: 8080
    ssl_port: 4433
    ssl_cert_file: /certs/server.crt
    ssl_key_file: /certs/server.key
Etcd:
    endpoints:
        - 127.0.0.1:2379
Service:
    