package public

import "github.com/gin-gonic/gin"

var SystemMenu = []gin.H{
	{
		"id":        12,
		"path":      "/document",
		"component": "",
		"name":      "文档",
		"meta": gin.H{
			"title":       "文档",
			"icon":        "ion:tv-outline",
			"isExt":       false,
			"extOpenMode": 1,
			"type":        0,
			"orderNo":     2,
			"show":        1,
			"activeMenu":  nil,
			"status":      1,
			"keepAlive":   0,
		},
		"redirect": "https://www.typeorm.org/",
		"children": []gin.H{
			{
				"id":   14,
				"path": "https://www.typeorm.org/",
				"name": "Typeorm中文文档(外链)",
				"meta": gin.H{
					"title":       "Typeorm中文文档(外链)",
					"icon":        "",
					"isExt":       true,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     3,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
			{
				"id":   15,
				"path": "https://docs.nestjs.cn/",
				"name": "Nest.js中文文档(内嵌)",
				"meta": gin.H{
					"title":       "Nest.js中文文档(内嵌)",
					"icon":        "",
					"isExt":       true,
					"extOpenMode": 2,
					"type":        1,
					"orderNo":     4,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
			{
				"id":   112,
				"path": "https://antdv.com/components/overview-cn",
				"name": "antdv文档(内嵌)",
				"meta": gin.H{
					"title":       "antdv文档(内嵌)",
					"icon":        "",
					"isExt":       true,
					"extOpenMode": 2,
					"type":        1,
					"orderNo":     255,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
		},
	},
	{
		"id":        1,
		"path":      "/system",
		"component": "",
		"name":      "系统管理",
		"meta": gin.H{
			"title":       "系统管理",
			"icon":        "ant-design:setting-outlined",
			"isExt":       false,
			"extOpenMode": 1,
			"type":        0,
			"orderNo":     254,
			"show":        1,
			"activeMenu":  nil,
			"status":      1,
			"keepAlive":   0,
		},
		"redirect": "/system/user",
		"children": []gin.H{
			{
				"id":        2,
				"path":      "/system/user",
				"name":      "用户管理",
				"component": "system/user/index",
				"meta": gin.H{
					"title":       "用户管理",
					"icon":        "ant-design:user-outlined",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     0,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
			{
				"id":        3,
				"path":      "/system/role",
				"name":      "角色管理",
				"component": "system/role/index",
				"meta": gin.H{
					"title":       "角色管理",
					"icon":        "ep:user",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     1,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
			{
				"id":        4,
				"path":      "/system/menu",
				"name":      "菜单管理",
				"component": "system/menu/index",
				"meta": gin.H{
					"title":       "菜单管理",
					"icon":        "ep:menu",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     2,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
			{
				"id":        61,
				"path":      "/system/dept",
				"name":      "部门管理",
				"component": "system/dept/index",
				"meta": gin.H{
					"title":       "部门管理",
					"icon":        "ant-design:deployment-unit-outlined",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     3,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
			{
				"id":        56,
				"path":      "/system/dict-type",
				"name":      "字典管理",
				"component": "system/dict-type/index",
				"meta": gin.H{
					"title":       "字典管理",
					"icon":        "ant-design:book-outlined",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     4,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
			{
				"id":        5,
				"path":      "/system/monitor",
				"component": "",
				"name":      "系统监控",
				"meta": gin.H{
					"title":       "系统监控",
					"icon":        "ep:monitor",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        0,
					"orderNo":     5,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
				"redirect": "/system/monitor/online",
				"children": []gin.H{
					{
						"id":        6,
						"path":      "/system/monitor/online",
						"name":      "在线用户",
						"component": "system/monitor/online/index",
						"meta": gin.H{
							"title":       "在线用户",
							"icon":        "",
							"isExt":       false,
							"extOpenMode": 1,
							"type":        1,
							"orderNo":     0,
							"show":        1,
							"activeMenu":  nil,
							"status":      1,
							"keepAlive":   0,
						},
					},
					{
						"id":        7,
						"path":      "/sys/monitor/login-log",
						"name":      "登录日志",
						"component": "system/monitor/log/login/index",
						"meta": gin.H{
							"title":       "登录日志",
							"icon":        "",
							"isExt":       false,
							"extOpenMode": 1,
							"type":        1,
							"orderNo":     0,
							"show":        1,
							"activeMenu":  nil,
							"status":      1,
							"keepAlive":   0,
						},
					},
					{
						"id":        68,
						"path":      "/health",
						"name":      "健康检查",
						"component": "",
						"meta": gin.H{
							"title":       "健康检查",
							"icon":        "",
							"isExt":       false,
							"extOpenMode": 1,
							"type":        1,
							"orderNo":     4,
							"show":        0,
							"activeMenu":  nil,
							"status":      1,
							"keepAlive":   0,
						},
					},
					{
						"id":        8,
						"path":      "/system/monitor/serve",
						"name":      "服务监控",
						"component": "system/monitor/serve/index",
						"meta": gin.H{
							"title":       "服务监控",
							"icon":        "",
							"isExt":       false,
							"extOpenMode": 1,
							"type":        1,
							"orderNo":     4,
							"show":        1,
							"activeMenu":  nil,
							"status":      1,
							"keepAlive":   0,
						},
					},
				},
			},
			{
				"id":        9,
				"path":      "/system/schedule",
				"component": "",
				"name":      "任务调度",
				"meta": gin.H{
					"title":       "任务调度",
					"icon":        "ant-design:schedule-filled",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        0,
					"orderNo":     6,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
				"redirect": "/system/task",
				"children": []gin.H{
					{
						"id":        10,
						"path":      "/system/task",
						"name":      "任务管理",
						"component": "system/schedule/task/index",
						"meta": gin.H{
							"title":       "任务管理",
							"icon":        "",
							"isExt":       false,
							"extOpenMode": 1,
							"type":        1,
							"orderNo":     0,
							"show":        1,
							"activeMenu":  nil,
							"status":      1,
							"keepAlive":   0,
						},
					},
					{
						"id":        11,
						"path":      "/system/task/log",
						"name":      "任务日志",
						"component": "system/schedule/log/index",
						"meta": gin.H{
							"title":       "任务日志",
							"icon":        "",
							"isExt":       false,
							"extOpenMode": 1,
							"type":        1,
							"orderNo":     0,
							"show":        1,
							"activeMenu":  nil,
							"status":      1,
							"keepAlive":   0,
						},
					},
				},
			},
			{
				"id":        107,
				"path":      "system/dict-item/:id",
				"name":      "字典项管理",
				"component": "system/dict-item/index",
				"meta": gin.H{
					"title":       "字典项管理",
					"icon":        "ant-design:facebook-outlined",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     255,
					"show":        0,
					"activeMenu":  "字典管理",
					"status":      1,
					"keepAlive":   0,
				},
			},
			{
				"id":        86,
				"path":      "/param-config",
				"name":      "参数配置",
				"component": "system/param-config/index",
				"meta": gin.H{
					"title":       "参数配置",
					"icon":        "ep:edit",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     255,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
		},
	},
	{
		"id":        48,
		"path":      "/tool",
		"component": "",
		"name":      "系统工具",
		"meta": gin.H{
			"title":       "系统工具",
			"icon":        "ant-design:tool-outlined",
			"isExt":       false,
			"extOpenMode": 1,
			"type":        0,
			"orderNo":     254,
			"show":        1,
			"activeMenu":  nil,
			"status":      1,
			"keepAlive":   0,
		},
		"redirect": "/tool/email",
		"children": []gin.H{
			{
				"id":        49,
				"path":      "/tool/email",
				"name":      "邮件工具",
				"component": "tool/email/index",
				"meta": gin.H{
					"title":       "邮件工具",
					"icon":        "ant-design:send-outlined",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     1,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
			{
				"id":        51,
				"path":      "/tool/storage",
				"name":      "存储管理",
				"component": "tool/storage/index",
				"meta": gin.H{
					"title":       "存储管理",
					"icon":        "ant-design:appstore-outlined",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     2,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
		},
	},
	{
		"id":        115,
		"path":      "netdisk",
		"component": nil,
		"name":      "网盘管理",
		"meta": gin.H{
			"title":       "网盘管理",
			"icon":        "ant-design:cloud-server-outlined",
			"isExt":       false,
			"extOpenMode": 1,
			"type":        0,
			"orderNo":     255,
			"show":        1,
			"activeMenu":  nil,
			"status":      1,
			"keepAlive":   0,
		},
		"redirect": "manage",
		"children": []gin.H{
			{
				"id":        116,
				"path":      "manage",
				"name":      "文件管理",
				"component": "netdisk/manage",
				"meta": gin.H{
					"title":       "文件管理",
					"icon":        "",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     252,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
			{
				"id":        127,
				"path":      "overview",
				"name":      "网盘概览",
				"component": "netdisk/overview",
				"meta": gin.H{
					"title":       "网盘概览",
					"icon":        "",
					"isExt":       false,
					"extOpenMode": 1,
					"type":        1,
					"orderNo":     254,
					"show":        1,
					"activeMenu":  nil,
					"status":      1,
					"keepAlive":   0,
				},
			},
		},
	},
	{
		"id":        43,
		"path":      "/about",
		"name":      "关于",
		"component": "account/about",
		"meta": gin.H{
			"title":       "关于",
			"icon":        "ant-design:info-circle-outlined",
			"isExt":       false,
			"extOpenMode": 1,
			"type":        1,
			"orderNo":     260,
			"show":        1,
			"activeMenu":  nil,
			"status":      1,
			"keepAlive":   0,
		},
	},
}

var SystemPermissions = []string{
	"system:user:list",
	"system:role:list",
	"system:menu:list",
	"system:online:list",
	"system:log:login:list",
	"system:serve:stat",
	"system:task:list",
	"system:user:create",
	"system:user:delete",
	"system:user:update",
	"system:user:read",
	"system:role:create",
	"system:role:delete",
	"system:role:update",
	"system:role:read",
	"system:menu:create",
	"system:menu:delete",
	"system:menu:update",
	"system:menu:read",
	"system:online:kick",
	"system:task:create",
	"system:task:delete",
	"system:task:once",
	"system:task:read",
	"system:task:start",
	"system:task:stop",
	"system:task:update",
	"system:log:task:list",
	"system:tools:email",
	"tools:email:send",
	"tool:storage:list",
	"upload:upload",
	"tool:storage:delete",
	"system:user:password",
	"system:dict-type:list",
	"system:dict-type:create",
	"system:dict-type:update",
	"system:dict-type:delete",
	"system:dict-type:info",
	"system:dept:list",
	"system:dept:create",
	"system:dept:update",
	"system:dept:delete",
	"system:dept:read",
	"app:health:network",
	"app:health: database",
	"system:param-config:list",
	"system:param-config:read",
	"system:param-config:create",
	"system:param-config:update",
	"system:param-config:delete",
	"system:dict-item:list",
	"system:dict-item:create",
	"system:dict-item:update",
	"system:dict-item:delete",
	"system:dict-item:info",
	"netdisk:manage:list",
	"netdisk:manage:create",
	"netdisk:manage:read",
	"netdisk:manage:update",
	"netdisk:manage:delete",
	"netdisk:manage:token",
	"netdisk:manage:mark",
	"netdisk:manage:download",
	"netdisk:manage:rename",
	"netdisk:manage:copy",
	"netdisk:manage:cut",
	"netdisk:overview:desc",
}
