package public

import "github.com/gin-gonic/gin"

var SystemMenu = []gin.H{
	{
		"id":        1,
		"path":      "/system/monitor/serve",
		"name":      "服务监控",
		"component": "system/monitor/serve/index",
		"meta": gin.H{
			"title":       "服务监控",
			"icon":        "ant-design:desktop-outlined",
			"isExt":       false,
			"extOpenMode": 1,
			"type":        1,
			"orderNo":     4,
			"show":        1,
			"activeMenu":  nil,
			"status":      1,
			"keepAlive":   0,
		},
	},
	{
		"id":   2,
		"path": "https://antdv.com/components/overview-cn",
		"name": "使用指南",
		"meta": gin.H{
			"title":       "使用指南",
			"icon":        "ion:tv-outline",
			"isExt":       true,
			"extOpenMode": 2,
			"type":        1,
			"orderNo":     255,
			"show":        1,
			"activeMenu":  nil,
			"status":      1,
			"keepAlive":   0,
		},
	},
	{
		"id":        3,
		"path":      "/about",
		"name":      "关于",
		"component": "account/about",
		"meta": gin.H{
			"title":       "关于",
			"icon":        "ant-design:info-circle-outlined",
			"isExt":       false,
			"extOpenMode": 1,
			"type":        1,
			"orderNo":     260,
			"show":        1,
			"activeMenu":  nil,
			"status":      1,
			"keepAlive":   0,
		},
	},
}

var SystemPermissions = []string{
	"system:user:list",
	"system:role:list",
	"system:menu:list",
	"system:online:list",
	"system:log:login:list",
	"system:serve:stat",
	"system:task:list",
	"system:user:create",
	"system:user:delete",
	"system:user:update",
	"system:user:read",
	"system:role:create",
	"system:role:delete",
	"system:role:update",
	"system:role:read",
	"system:menu:create",
	"system:menu:delete",
	"system:menu:update",
	"system:menu:read",
	"system:online:kick",
	"system:task:create",
	"system:task:delete",
	"system:task:once",
	"system:task:read",
	"system:task:start",
	"system:task:stop",
	"system:task:update",
	"system:log:task:list",
	"system:tools:email",
	"tools:email:send",
	"tool:storage:list",
	"upload:upload",
	"tool:storage:delete",
	"system:user:password",
	"system:dict-type:list",
	"system:dict-type:create",
	"system:dict-type:update",
	"system:dict-type:delete",
	"system:dict-type:info",
	"system:dept:list",
	"system:dept:create",
	"system:dept:update",
	"system:dept:delete",
	"system:dept:read",
	"app:health:network",
	"app:health: database",
	"system:param-config:list",
	"system:param-config:read",
	"system:param-config:create",
	"system:param-config:update",
	"system:param-config:delete",
	"system:dict-item:list",
	"system:dict-item:create",
	"system:dict-item:update",
	"system:dict-item:delete",
	"system:dict-item:info",
	"netdisk:manage:list",
	"netdisk:manage:create",
	"netdisk:manage:read",
	"netdisk:manage:update",
	"netdisk:manage:delete",
	"netdisk:manage:token",
	"netdisk:manage:mark",
	"netdisk:manage:download",
	"netdisk:manage:rename",
	"netdisk:manage:copy",
	"netdisk:manage:cut",
	"netdisk:overview:desc",
}
