// Code generated by swaggo/swag. DO NOT EDIT.

package v1

import "github.com/swaggo/swag"

const docTemplatev1 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "stone2401@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/admin_info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取admin信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminApi"
                ],
                "summary": "admin基本信息",
                "operationId": "/admin/admin_info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminInfoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/change_pwd": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminApi"
                ],
                "summary": "admin密码修改",
                "operationId": "/admin/change_pwd",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminChangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin_login/login": {
            "post": {
                "description": "描述",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "adminApi"
                ],
                "summary": "admin登录接口",
                "operationId": "/admin_login/login",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminLoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/app_add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "添加用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "添加用户",
                "operationId": "/app/app_add",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AppListItem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/app_delete": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户删除",
                "operationId": "/app/app_delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/app_detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户详情",
                "operationId": "/app/app_detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.App"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/app_list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户列表",
                "operationId": "/app/app_list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询词汇",
                        "name": "info",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "page_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "条数",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AppListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/app_stat": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户统计",
                "operationId": "/app/app_stat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/app_update": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "修改用户",
                "operationId": "/app/app_update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AppListItem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/dashboard/flowStat": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "指标统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大盘"
                ],
                "summary": "指标统计",
                "operationId": "/dashboard/flowStat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServiceStatResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/dashboard/panelGroupData": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "指标统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大盘"
                ],
                "summary": "指标统计",
                "operationId": "/dashboard/panelGroupData",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PanelGroupDataResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/dashboard/service_stat": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "指标统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大盘"
                ],
                "summary": "指标统计",
                "operationId": "/dashboard/service_stat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServiceStatAllResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "检测接口",
                "tags": [
                    "api-v1"
                ],
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/service/service_add_grpc": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "添加hGrpc服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "添加hGrpc服务",
                "operationId": "/service/service_add_grpc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceAddGrpcRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/service_add_http": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "添加http服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "添加http服务",
                "operationId": "/service/service_add_http",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceAddHttpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/service_add_tcp": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "添加tcp服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "添加tcp服务",
                "operationId": "/service/service_add_tcp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceAddTcpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/service_delete": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "服务删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "服务删除",
                "operationId": "/service/service_delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/service_detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "服务详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "服务详情",
                "operationId": "/service/service_detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServiceUpdateGrpcRequest"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/service_list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "服务列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "服务列表",
                "operationId": "/service/service_list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "info",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "page_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "个数",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServiceListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/service_stat": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "服务统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "服务统计",
                "operationId": "/service/service_stat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServiceStatResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/service_update_grpc": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改tcp服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "修改grpc服务",
                "operationId": "/service/service_update_grpc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceUpdateGrpcRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/service_update_http": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改http服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "修改http服务",
                "operationId": "/service/service_update_http",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceUpdateHttpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/service_update_tcp": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改tcp服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "修改tcp服务",
                "operationId": "/service/service_update_tcp",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceUpdateTcpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.ResponseErr"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dao.App": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "create_at": {
                    "type": "string"
                },
                "delete_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_delete": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "update_at": {
                    "type": "string"
                },
                "white_ips": {
                    "type": "string"
                }
            }
        },
        "dto.AdminChangeRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "dto.AdminInfoResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "introduction": {
                    "type": "string"
                },
                "login_time": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.AdminLoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "admin"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dto.AdminLoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.AppListItem": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                },
                "real_qpd": {
                    "type": "integer"
                },
                "real_qps": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "white_ips": {
                    "type": "string"
                }
            }
        },
        "dto.AppListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AppListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.PanelGroupDataResponse": {
            "type": "object",
            "properties": {
                "app_num": {
                    "type": "integer"
                },
                "current_qps": {
                    "type": "integer"
                },
                "service_num": {
                    "type": "integer"
                },
                "today_request_num": {
                    "type": "integer"
                }
            }
        },
        "dto.ServiceAddGrpcRequest": {
            "type": "object",
            "properties": {
                "black_list": {
                    "description": "黑名单",
                    "type": "string",
                    "example": ""
                },
                "clientip_flow_limit": {
                    "description": "客户端ip限流",
                    "type": "integer",
                    "example": 0
                },
                "forbid_list": {
                    "description": "禁用ip列表",
                    "type": "string",
                    "example": ""
                },
                "header_transfor": {
                    "description": "header转换支持增加(add)、删除(del)、修改(edit) 格式: add headname headvalue 多个逗号间隔",
                    "type": "string",
                    "example": ""
                },
                "ip_list": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "47.113.203.197:2401"
                },
                "open_auth": {
                    "description": "service_access_control 表字段",
                    "type": "boolean",
                    "example": false
                },
                "port": {
                    "description": "service_hrrp_rule 表字段",
                    "type": "integer"
                },
                "round_type": {
                    "description": "service_load_balance 表字段",
                    "type": "integer",
                    "example": 0
                },
                "service_desc": {
                    "description": "服务描述",
                    "type": "string",
                    "example": "必填 服务描述"
                },
                "service_flow_limit": {
                    "description": "服务的限流",
                    "type": "integer",
                    "example": 0
                },
                "service_name": {
                    "description": "service_info 表字段",
                    "type": "string",
                    "example": "必填 服务名称"
                },
                "upstream_connect_timeout": {
                    "description": "建立连接超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_header_timeout": {
                    "description": "获取header超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_idle_timeout": {
                    "description": "链接最大空闲时间, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_max_idle": {
                    "description": "最大空闲链接数",
                    "type": "integer",
                    "example": 0
                },
                "weight_list": {
                    "description": "权重列表",
                    "type": "string",
                    "example": "10"
                },
                "white_list": {
                    "description": "白名单",
                    "type": "string",
                    "example": ""
                }
            }
        },
        "dto.ServiceAddHttpRequest": {
            "type": "object",
            "properties": {
                "black_list": {
                    "description": "黑名单",
                    "type": "string",
                    "example": ""
                },
                "clientip_flow_limit": {
                    "description": "客户端ip限流",
                    "type": "integer",
                    "example": 0
                },
                "forbid_list": {
                    "description": "禁用ip列表",
                    "type": "string",
                    "example": ""
                },
                "header_transfor": {
                    "description": "header转换支持增加(add)、删除(del)、修改(edit) 格式: add headname headvalue 多个逗号间隔",
                    "type": "string",
                    "example": ""
                },
                "ip_list": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "47.113.203.197:2401"
                },
                "need_https": {
                    "description": "支持https 1=支持",
                    "type": "boolean",
                    "example": false
                },
                "need_strip_url": {
                    "description": "启用strip_uri 1=启用",
                    "type": "boolean",
                    "example": false
                },
                "need_websocket": {
                    "description": "是否支持websocket 1=支持",
                    "type": "boolean",
                    "example": false
                },
                "open_auth": {
                    "description": "service_access_control 表字段",
                    "type": "boolean",
                    "example": false
                },
                "round_type": {
                    "description": "service_load_balance 表字段",
                    "type": "integer",
                    "example": 0
                },
                "rule": {
                    "description": "type=domain表示域名，type=url_prefix时表示url前缀",
                    "type": "string",
                    "example": "必填 域名或后缀"
                },
                "rule_type": {
                    "description": "匹配类型 0=url前缀url_prefix 1=域名domain",
                    "type": "integer",
                    "example": 0
                },
                "service_desc": {
                    "description": "服务描述",
                    "type": "string",
                    "example": "必填 服务描述"
                },
                "service_flow_limit": {
                    "description": "服务的限流",
                    "type": "integer",
                    "example": 0
                },
                "service_name": {
                    "description": "service_info 表字段",
                    "type": "string",
                    "example": "必填 服务名称"
                },
                "upstream_connect_timeout": {
                    "description": "建立连接超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_header_timeout": {
                    "description": "获取header超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_idle_timeout": {
                    "description": "链接最大空闲时间, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_max_idle": {
                    "description": "最大空闲链接数",
                    "type": "integer",
                    "example": 0
                },
                "url_rewrite": {
                    "description": "url重写功能 格式：^/gatekeeper/test_service(.*) $1 多个逗号间隔",
                    "type": "string",
                    "example": ""
                },
                "weight_list": {
                    "description": "权重列表",
                    "type": "string",
                    "example": "10"
                },
                "white_list": {
                    "description": "白名单",
                    "type": "string",
                    "example": ""
                }
            }
        },
        "dto.ServiceAddTcpRequest": {
            "type": "object",
            "properties": {
                "black_list": {
                    "description": "黑名单",
                    "type": "string",
                    "example": ""
                },
                "clientip_flow_limit": {
                    "description": "客户端ip限流",
                    "type": "integer",
                    "example": 0
                },
                "forbid_list": {
                    "description": "禁用ip列表",
                    "type": "string",
                    "example": ""
                },
                "ip_list": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "47.113.203.197:2401"
                },
                "open_auth": {
                    "description": "service_access_control 表字段",
                    "type": "boolean",
                    "example": false
                },
                "port": {
                    "description": "service_hrrp_rule 表字段",
                    "type": "integer"
                },
                "round_type": {
                    "description": "service_load_balance 表字段",
                    "type": "integer",
                    "example": 0
                },
                "service_desc": {
                    "description": "服务描述",
                    "type": "string",
                    "example": "必填 服务描述"
                },
                "service_flow_limit": {
                    "description": "服务的限流",
                    "type": "integer",
                    "example": 0
                },
                "service_name": {
                    "description": "service_info 表字段",
                    "type": "string",
                    "example": "必填 服务名称"
                },
                "upstream_connect_timeout": {
                    "description": "建立连接超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_header_timeout": {
                    "description": "获取header超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_idle_timeout": {
                    "description": "链接最大空闲时间, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_max_idle": {
                    "description": "最大空闲链接数",
                    "type": "integer",
                    "example": 0
                },
                "weight_list": {
                    "description": "权重列表",
                    "type": "string",
                    "example": "10"
                },
                "white_list": {
                    "description": "白名单",
                    "type": "string",
                    "example": ""
                }
            }
        },
        "dto.ServiceListItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "load_type": {
                    "type": "integer"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                },
                "service_addr": {
                    "type": "string"
                },
                "service_desc": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                },
                "total_node": {
                    "type": "integer"
                }
            }
        },
        "dto.ServiceListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ServiceListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ServiceStatAllItemResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "dto.ServiceStatAllResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ServiceStatAllItemResponse"
                    }
                },
                "legend": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.ServiceStatResponse": {
            "type": "object",
            "properties": {
                "today": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "yesterday": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.ServiceUpdateGrpcRequest": {
            "type": "object",
            "properties": {
                "black_list": {
                    "description": "黑名单",
                    "type": "string",
                    "example": ""
                },
                "clientip_flow_limit": {
                    "description": "客户端ip限流",
                    "type": "integer",
                    "example": 0
                },
                "forbid_list": {
                    "description": "禁用ip列表",
                    "type": "string",
                    "example": ""
                },
                "header_transfor": {
                    "description": "header转换支持增加(add)、删除(del)、修改(edit) 格式: add headname headvalue 多个逗号间隔",
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "integer"
                },
                "ip_list": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "47.113.203.197:2401"
                },
                "open_auth": {
                    "description": "service_access_control 表字段",
                    "type": "boolean",
                    "example": false
                },
                "port": {
                    "description": "service_hrrp_rule 表字段",
                    "type": "integer"
                },
                "round_type": {
                    "description": "service_load_balance 表字段",
                    "type": "integer",
                    "example": 0
                },
                "service_desc": {
                    "description": "服务描述",
                    "type": "string",
                    "example": "必填 服务描述"
                },
                "service_flow_limit": {
                    "description": "服务的限流",
                    "type": "integer",
                    "example": 0
                },
                "service_name": {
                    "description": "service_info 表字段",
                    "type": "string",
                    "example": "必填 服务名称"
                },
                "upstream_connect_timeout": {
                    "description": "建立连接超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_header_timeout": {
                    "description": "获取header超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_idle_timeout": {
                    "description": "链接最大空闲时间, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_max_idle": {
                    "description": "最大空闲链接数",
                    "type": "integer",
                    "example": 0
                },
                "weight_list": {
                    "description": "权重列表",
                    "type": "string",
                    "example": "10"
                },
                "white_list": {
                    "description": "白名单",
                    "type": "string",
                    "example": ""
                }
            }
        },
        "dto.ServiceUpdateHttpRequest": {
            "type": "object",
            "properties": {
                "black_list": {
                    "description": "黑名单",
                    "type": "string",
                    "example": ""
                },
                "clientip_flow_limit": {
                    "description": "客户端ip限流",
                    "type": "integer",
                    "example": 0
                },
                "forbid_list": {
                    "description": "禁用ip列表",
                    "type": "string",
                    "example": ""
                },
                "header_transfor": {
                    "description": "header转换支持增加(add)、删除(del)、修改(edit) 格式: add headname headvalue 多个逗号间隔",
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "integer"
                },
                "ip_list": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "47.113.203.197:2401"
                },
                "need_https": {
                    "description": "支持https 1=支持",
                    "type": "boolean",
                    "example": false
                },
                "need_strip_url": {
                    "description": "启用strip_uri 1=启用",
                    "type": "boolean",
                    "example": false
                },
                "need_websocket": {
                    "description": "是否支持websocket 1=支持",
                    "type": "boolean",
                    "example": false
                },
                "open_auth": {
                    "description": "service_access_control 表字段",
                    "type": "boolean",
                    "example": false
                },
                "round_type": {
                    "description": "service_load_balance 表字段",
                    "type": "integer",
                    "example": 0
                },
                "rule": {
                    "description": "type=domain表示域名，type=url_prefix时表示url前缀",
                    "type": "string",
                    "example": "必填 域名或后缀"
                },
                "rule_type": {
                    "description": "匹配类型 0=url前缀url_prefix 1=域名domain",
                    "type": "integer",
                    "example": 0
                },
                "service_desc": {
                    "description": "服务描述",
                    "type": "string",
                    "example": "必填 服务描述"
                },
                "service_flow_limit": {
                    "description": "服务的限流",
                    "type": "integer",
                    "example": 0
                },
                "service_name": {
                    "description": "service_info 表字段",
                    "type": "string",
                    "example": "必填 服务名称"
                },
                "upstream_connect_timeout": {
                    "description": "建立连接超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_header_timeout": {
                    "description": "获取header超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_idle_timeout": {
                    "description": "链接最大空闲时间, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_max_idle": {
                    "description": "最大空闲链接数",
                    "type": "integer",
                    "example": 0
                },
                "url_rewrite": {
                    "description": "url重写功能 格式：^/gatekeeper/test_service(.*) $1 多个逗号间隔",
                    "type": "string",
                    "example": ""
                },
                "weight_list": {
                    "description": "权重列表",
                    "type": "string",
                    "example": "10"
                },
                "white_list": {
                    "description": "白名单",
                    "type": "string",
                    "example": ""
                }
            }
        },
        "dto.ServiceUpdateTcpRequest": {
            "type": "object",
            "properties": {
                "black_list": {
                    "description": "黑名单",
                    "type": "string",
                    "example": ""
                },
                "clientip_flow_limit": {
                    "description": "客户端ip限流",
                    "type": "integer",
                    "example": 0
                },
                "forbid_list": {
                    "description": "禁用ip列表",
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "integer"
                },
                "ip_list": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "47.113.203.197:2401"
                },
                "open_auth": {
                    "description": "service_access_control 表字段",
                    "type": "boolean",
                    "example": false
                },
                "port": {
                    "description": "service_hrrp_rule 表字段",
                    "type": "integer"
                },
                "round_type": {
                    "description": "service_load_balance 表字段",
                    "type": "integer",
                    "example": 0
                },
                "service_desc": {
                    "description": "服务描述",
                    "type": "string",
                    "example": "必填 服务描述"
                },
                "service_flow_limit": {
                    "description": "服务的限流",
                    "type": "integer",
                    "example": 0
                },
                "service_name": {
                    "description": "service_info 表字段",
                    "type": "string",
                    "example": "必填 服务名称"
                },
                "upstream_connect_timeout": {
                    "description": "建立连接超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_header_timeout": {
                    "description": "获取header超时, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_idle_timeout": {
                    "description": "链接最大空闲时间, 单位s",
                    "type": "integer",
                    "example": 0
                },
                "upstream_max_idle": {
                    "description": "最大空闲链接数",
                    "type": "integer",
                    "example": 0
                },
                "weight_list": {
                    "description": "权重列表",
                    "type": "string",
                    "example": "10"
                },
                "white_list": {
                    "description": "白名单",
                    "type": "string",
                    "example": ""
                }
            }
        },
        "middleware.ResponseErr": {
            "type": "object",
            "properties": {
                "data": {},
                "errmsg": {
                    "type": "string"
                },
                "errno": {
                    "type": "integer"
                },
                "stack": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfov1 holds exported Swagger Info so clients can modify it
var SwaggerInfov1 = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:2401",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "轻量级网关",
	Description:      "一个轻量级网关代理，支持多种代理协议，接口转发，数据统计，带有管理界面",
	InfoInstanceName: "v1",
	SwaggerTemplate:  docTemplatev1,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfov1.InstanceName(), SwaggerInfov1)
}
